carlaKC/jam-ln

Cargo.lock, ln-resource-mgr/src/lib.rs, ln-resource-mgr/src/outgoing_reputation.rs, ln-simln-jamming/Cargo.toml, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/sink_interceptor.rs
Add a check that at startup:
* The target has reputation with 50% of its pairs
* The attacker has reputation with 50% of the target's peers
TODO:  check reputation for some htlc amount (eg $10) so that we don't hit reputations that are _just_ over the threshold
It's not worth running a simulation if we don't start with _some_ reputation, because we're not really testing a sink attack if they don't.
=> multi: check reputation at start of simulation to ensure worth running

ln-resource-mgr/src/outgoing_reputation.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/sink_interceptor.rs
Since reputation is assessed for a specific htlc, it makes sense to add a htlc amount to our reputation checks - ie, a peer is considered to have good reputation if they can get a htlc of size X endorsed.
This helps to filter out cases where a reputation pair is _just_  positive but can't actually get any meaningfully sized htlcs endorsed.
=> multi: Add a htlc amount to reputation checks

Cargo.lock, ln-resource-mgr/src/outgoing_reputation.rs, ln-simln-jamming/Cargo.toml, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/revenue_interceptor.rs, ln-simln-jamming/src/sink_interceptor.rs
* Trait objects aren't necessary for clock; we don't need to use hetrogenous erased impls of the trait
* Fix incorrect block speed constant
* Use incoming expiry height rather than cltv delta for opportunity cost (we want the number of blocks that the htlc can be held for from the current height, and simln doesn't set a block heigh so `incoming_expiry - height = incoming_expiry`)
=> multi: switch to generics for clock and fixup cltv

Cargo.lock, ln-resource-mgr/Cargo.toml, ln-resource-mgr/src/lib.rs, ln-resource-mgr/src/outgoing_reputation.rs, ln-simln-jamming/src/analysis.rs, ln-simln-jamming/src/lib.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/sink_interceptor.rs, ln-simln-jamming/src/test_utils.rs
* Add the ability to specify a set of nodes that we're interested in writing their forwards to disk
* This is done in `reputation_interceptor` because this is where we have access to interesting reputation numbers
* To get general jams to be reported, the `reputation_interceptor` is updated to assign no general resources to some nodes, which will result in them being bounced by the `reputation_interceptor` rather than needing to rely on custom logic in `sink_interceptor`
=> multi: write results to file and use reputation interceptor to general jam

ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/htlc_manager.rs, ln-resource-mgr/src/lib.rs, ln-resource-mgr/src/outgoing_channel.rs, ln-resource-mgr/src/outgoing_reputation.rs, ln-simln-jamming/src/analysis.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/sink_interceptor.rs, ln-simln-jamming/src/test_utils.rs
For congestion bucket + incoming reputation it's easier to have a central record of htlcs rather than stashing them on the outgoing channel.
=> refactor: move htlc tracking into single htlc manager

ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/htlc_manager.rs, ln-resource-mgr/src/incoming_channel.rs, ln-resource-mgr/src/lib.rs, ln-resource-mgr/src/outgoing_channel.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/test_utils.rs
When our general resources are full, it's likely that we're under attack of some kind.
This PR adds a "congestion" bucket which is only used when general is saturated. Nodes may use resources in this bucket with the following restrictions:
* They only consume one slot at a time, and htlcs may be no larger than `bucket liquidity / bucket slots`
* In the last 2 weeks, they have not used the congestion resources for a htlc that was held for > 90s
* The incoming HTLC was endorsed
This bucket attempts to give honest peers a shot at resources, even if they don't have reputation. It can't be easily abused by attackers because usage is very limited (one congestion slot per inbound across all of our outbound), and to try abuse it through another peer the attacker has to gain reputation with the …
=> Add congestion bucket for attack times

ln-simln-jamming/src/main.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/sink_interceptor.rs
Depends on #32 
Some changes to test how our reputation bounces back with congestion resources in play:
- General jam `target -> peer` edges, so that target needs to use congestion resources
- Only shutdown when attacker has lost reputation *and* the target's reputation has recovered to similar to start
- Reputations couldn't be ruined, and the attack failed
- Reputations bounded back, so recovery is working
- Revenue check for shutdown remains unchanged
- Hold HTLCs for full incoming expiry
=> Extend simulation to utilize congestion and recover

ln-simln-jamming/src/attack_interceptor.rs, ln-simln-jamming/src/lib.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs
In preparation for #36, do some renaming and refactoring.
* We call things `incoming_revenue` in a lot of places, which is confusing when we're actually tracking this bidirectinally.
* Rename sink-specific files/structs
* Move to a more generic `list_channels` vs `list_reputation_pairs`
=> prefactor: prepare for pulling attack out into module

ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/incoming_channel.rs, ln-resource-mgr/src/lib.rs, ln-simln-jamming/src/analysis.rs, ln-simln-jamming/src/attack_interceptor.rs, ln-simln-jamming/src/lib.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/test_utils.rs
This PR adds incoming reputation. 
When assessing an htlc, The `ForwardManager` now returns an `AllocationCheck` that includes values to check both incoming and outgoing reputation. 
The option to do either incoming or outgoing or both can be passed to the reputation and forward manager and it will do the checks accordingly when deciding to add a new htlc.
=> implement incoming reputation

Makefile, ln-simln-jamming/Cargo.toml
Add to makefile in a separate command. In future I can see us adding additional tooling binaries (such as one to generate the bootstrap data), so putting this under a generic title in preparation.
=> makefile: install reputation_builder in install-tools command

README.md, ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/htlc_manager.rs, ln-resource-mgr/src/incoming_channel.rs, ln-resource-mgr/src/lib.rs, ln-resource-mgr/src/outgoing_channel.rs, ln-simln-jamming/src/analysis.rs, ln-simln-jamming/src/attack_interceptor.rs, ln-simln-jamming/src/attacks/mod.rs, ln-simln-jamming/src/attacks/sink.rs, ln-simln-jamming/src/bin/reputation_builder.rs, ln-simln-jamming/src/lib.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/test_utils.rs
prefactor for https://github.com/carlaKC/jam-ln/issues/56
diff is a bit big but changes are:
- remove incoming reputation: Left as how it was before incoming reputation was added.
- renamed 1:1 from endorsement to accountability. As is, it does not match the proposal. As I was going through the code, added notes here: https://github.com/carlaKC/jam-ln/issues/56#issuecomment-2891424489 of things I think should change. Will continue updating that if I find anything else.
=> remove incoming reputation and rename accountability

ln-simln-jamming/src/lib.rs, ln-simln-jamming/src/main.rs
Current logging location duplicates this log on startup because we call it both in main and in our attack's reputation check.
Closes #50
=> ln-simln-jamming: move logging out of check_reputation_status

ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/htlc_manager.rs, ln-resource-mgr/src/incoming_channel.rs, ln-resource-mgr/src/lib.rs, ln-resource-mgr/src/outgoing_channel.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/test_utils.rs
as part of https://github.com/carlaKC/jam-ln/issues/56, changed the bucketing to be applied on the incoming channel instead of outgoing. 
changes done:
- moved the bucket params from `OutgoingChannel` to `IncomingChannel`
- check misuse of congestion bucket on the outgoing channel instead of incoming
- added protected bucket to `IncomingChannel`
- slipped in a couple tests to `ForwardManager`
doing this before https://github.com/carlaKC/jam-ln/pull/62 so that I could add the protected bucket and use it for that PR. Also, the tests added in `ForwardManager` are incomplete but should be expanded on https://github.com/carlaKC/jam-ln/pull/62 when the correct bucketing outcomes are implemented.
=> use buckets on incoming channel

ln-simln-jamming/src/attack_interceptor.rs, ln-simln-jamming/src/lib.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/test_utils.rs
I hope I'm not missing something but while doing some changes to the `ForwardManager` I noticed these methods were not used.  Perhaps they were added to help in testing? Anyhow, I think these are not needed but lmk if I'm wrong.
edit: Also looked into deleting `get_forwarding_outcome` on the `ReputationManager` which is also not used but I think could be.
=> remove unused check_htlc_outcome

ln-resource-mgr/src/lib.rs, ln-simln-jamming/src/bin/reputation_builder.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs
for https://github.com/carlaKC/jam-ln/issues/53, forward htlcs in congested bucket as `Accountable`.
And do bucket assignments in `inner_forwarding_outcome` as specified in latest proposal. 
Returning bucket assignment with this logic:
- if htlc is `unaccountable`:
- if general resources available, assign to general bucket.
- if congestion eligible and congestion resources available, assign to congestion bucket.
- if no general or congestion resources available:
- if peer has reputation, assign to protected bucket.
- if no reputation, fail with no resources.
- if htlc is `accountable` 
- check if peer has reputation and if so, assign to protected bucket. If no protected resources available, check general and then congestion. 
- if no reputation, fail with no reputation error. 
Modified …
=> Congestion accountable and bucket assigments

ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/htlc_manager.rs, ln-resource-mgr/src/lib.rs, ln-resource-mgr/src/outgoing_channel.rs, ln-simln-jamming/src/analysis.rs, ln-simln-jamming/src/reputation_interceptor.rs
Returning both the accountable signal on the forward and the bucket where the htlc was assigned. This is needed because when adding an htlc with `add_htlc` we need to use the accountable signal on the outgoing forward instead of reusing the incoming one since the signal can be upgraded. 
This changed the API a bit on the return types from a couple of methods. Particularly on `add_htlc` it is returning the `ForwardingOutcome` instead of `AllocationCheck`. I think this better reflects the outcome of the method. If an `AllocationCheck` is needed, we can get it from `get_allocation_snapshot`. 
This also introduces changes to match the accountable signals that should forwarded based on the bucket and incoming signal as specified in the proposal. 
<s>Changes related to this PR are in last 3 …
=> forward outcome from add_htlc

ln-simln-jamming/src/attack_interceptor.rs, ln-simln-jamming/src/main.rs
remove the `Mutex` on the attack interceptor. Should be up to each `JammingAttack` impl to be able to call `intercept_attacker_htlc` safely 
Fixes https://github.com/carlaKC/jam-ln/issues/75
=> ln-simln-jamming: remove mutex on attack interceptor

Cargo.lock, ln-resource-mgr/src/forward_manager.rs, ln-simln-jamming/Cargo.toml, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/test_utils.rs
very small  things I've stumbled upon while implementing a `JammingAttack`, mainly:
- <s> remove mutex on `reputation_interceptor` since `ReputationInterceptor` already mutexes on its fields.</s>
- add `GeneralChannelJammer` trait to jam a channel on a specific direction. 
- impl it on the `ReputationInterceptor`.  I think this is useful for jamming attacks that will like to jam a channel at any arbitrary point instead of only at the beginning
=> GeneralChannelJammer trait on the ReputationInterceptor

Cargo.lock, ln-simln-jamming/Cargo.toml, ln-simln-jamming/src/attack_interceptor.rs, ln-simln-jamming/src/attacks/mod.rs, ln-simln-jamming/src/attacks/sink.rs, ln-simln-jamming/src/main.rs
Improve separation of concerns for attack implementations - generally the actions taken for forwards will be different to receives, so we split them up to save implementations from having to branch all their logic on whether it's a forward or not.
=> ln-simln-jamming: add attacker receive interceptor

Cargo.lock, Makefile, ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/htlc_manager.rs, ln-simln-jamming/Cargo.toml, ln-simln-jamming/src/analysis.rs, ln-simln-jamming/src/bin/forward_builder.rs, ln-simln-jamming/src/bin/reputation_builder.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs
Add a new tool that can produce a single file with all forwards for the graph provided to bootstrap reputation. This can be paired with `reputation-builder` to generate summaries of the forwarding data for different bootstrap periods.
=> tools: Add forward generation tool for generating history

.gitignore, README.md, ln-simln-jamming/src/attacks/sink.rs, ln-simln-jamming/src/bin/forward_builder.rs, ln-simln-jamming/src/bin/reputation_builder.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs, ln-simln-jamming/src/revenue_interceptor.rs, ln-simln-jamming/src/test_utils.rs
This PR introduces two key changes:
1. Network directory: enforce a fixed structure for the simulation files that we expect, so that end users can simply specify a `--network` option which will look for the files that we need.
2. No bootstrap: allow the simulation to run without any attacker bootstrap, only bootstrapping honest nodes and starting the attacker off with zero reputation.
Fixes #84
=> Allow Running without Attacker Bootstrap

ln-simln-jamming/src/bin/reputation_builder.rs
We should be pulling our history for the full reputation-building period so that peers can build reputation properly.
=> ln-simln-jamming/bugfix: pull history for full reputation period

ln-resource-mgr/src/forward_manager.rs, ln-resource-mgr/src/incoming_channel.rs, ln-resource-mgr/src/lib.rs, ln-simln-jamming/src/attacks/utils.rs, ln-simln-jamming/src/bin/reputation_builder.rs, ln-simln-jamming/src/lib.rs, ln-simln-jamming/src/parsing.rs, ln-simln-jamming/src/reputation_interceptor.rs
Previously, we would add the revenue for a HTLC forward to both its incoming and outgoing channel's revenue target.
This PR updates tracking to only attribute HTLC fees to the revenue of the incoming channel that delivered it to our node.
=> Only track revenue threshold in one direction

ln-simln-jamming/src/analysis.rs, ln-simln-jamming/src/main.rs, ln-simln-jamming/src/parsing.rs
* Rename reputation sub-dirs to just be expressed in seconds, because humantime led to values like "5 months 7 days and 1 minute"
* Include all buckets liquidity / slots reporting in data output per node
* Write bootstrap period to simulation summary
=> trivial: renames and data adjustments

Cargo.lock, ln-simln-jamming/Cargo.toml, ln-simln-jamming/src/attacks/utils.rs
With this version on sim-ln, we'll no longer include the attacker's "excluded" channels in our random activity generation. This prevents the simulation from sending more payments in the attack time graph than it would it the peacetime graph (which would make us over-estimate revenue under attack).
=> ln-simln-jamming: bump sim-ln dependency to include exclude fix
